const books = [
  {
    id: 1,
    title: "Filosofi Kucing dalam Desain UX",
    author: "Dr. Meow",
    year: 2023,
    description: "Mengungkap bagaimana perilaku kucing—dari tidur 18 jam hingga menjatuhkan barang—dapat menjadi inspirasi fundamental dalam menciptakan user experience yang intuitif.",
    image: "https://placehold.co/300x400/7E57C2/white?text=Filosofi\\nKucing",
  },
  {
    id: 2,
    title: "Meracik Kopi dengan Kode",
    author: "Espresso Coder",
    year: 2022,
    description: "Panduan lengkap untuk mengotomatisasi mesin kopi Anda menggunakan Python dan Raspberry Pi. Termasuk bab bonus: 'Debugging Rasa Pahit'.",
    image: "https://placehold.co/300x400/A1887F/white?text=Kopi+Kode",
  },
  {
    id: 3,
    title: "Memahat Algoritma di Awan Piksel",
    author: "A.I.rtist",
    year: 2024,
    description: "Sebuah perjalanan artistik tentang bagaimana machine learning dapat digunakan untuk menciptakan karya seni generatif yang sureal dan memukau.",
    image: "https://placehold.co/300x400/26A69A/white?text=Seni+AI",
  },
  {
    id: 4,
    title: "Jaringan Saraf Tiruan & Ramalan Rasa Indomie",
    author: "Prof. Gurih",
    year: 2021,
    description: "Studi kasus mendalam tentang penggunaan deep learning untuk memprediksi kombinasi topping Indomie terpopuler di masa depan.",
    image: "https://placehold.co/300x400/FF7043/white?text=Rasa\\nIndomie",
  },
  {
    id: 5,
    title: "Meditasi Zen untuk Keyboard Mechanical",
    author: "Clicky Clack",
    year: 2023,
    description: "Temukan kedamaian batin melalui ritme ketikan. Buku ini mengajarkan cara mencapai pencerahan melalui suara 'thock' dan 'clack'.",
    image: "https://placehold.co/300x400/5C6BC0/white?text=Zen+Keyboard",
  },
  {
    id: 6,
    title: "CSS: Cara Centering Tiga Div Tanpa Nangis",
    author: "Flexbox Master",
    year: 2020,
    description: "Buku legendaris yang memecahkan misteri terbesar dalam pengembangan web. Spoiler: jawabannya bukan `margin: auto;` saja.",
    image: "https://placehold.co/300x400/42A5F5/white?text=CSS+Mastery",
  },
  {
    id: 7,
    title: "Teori Konspirasi Komentar Kode",
    author: "Anonymous C.",
    year: 2022,
    description: "Membongkar pesan-pesan tersembunyi yang ditinggalkan oleh programmer kuno dalam komentar kode. Apakah `// TODO: fix this later` adalah kode rahasia?",
    image: "https://placehold.co/300x400/26C6DA/white?text=Kode\\nRahasia",
  },
  {
    id: 8,
    title: "Bertahan Hidup di Hutan Belantara Stack Overflow",
    author: "Jane Doe",
    year: 2019,
    description: "Panduan esensial untuk para developer junior. Pelajari cara bertanya tanpa ditandai sebagai 'duplikat' dan cara menyalin jawaban dengan elegan.",
    image: "https://placehold.co/300x400/8D6E63/white?text=Stack\\nSurvivor",
  },
  {
    id: 9,
    title: "Quantum Computing untuk Pemalas",
    author: "Schrödinger's Coder",
    year: 2025,
    description: "Penjelasan superposisi dan keterikatan kuantum menggunakan analogi sederhana: status sebuah task, yang bisa jadi selesai dan belum selesai pada saat yang sama.",
    image: "https://placehold.co/300x400/66BB6A/white?text=Quantum\\nLazy",
  },
];

export default books;